backend:
  name: git-gateway

media_folder: "site/static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "pages"
    label: "Pages"
    editor: 
     preview: false
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          - {label: "Header", name: header, widget: object, fields: [
              {label: Title, name: title, widget: string},
              {label: Button, name: button, widget: string},
              {label: ButtonLink, name: buttonLink, widget: string}]}
          - {label: "Why Balloon", name: whyBalloon, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Reasons", name: "reasons", widget: "list", fields: [
                {label: "Image", name: "reasonImage", widget: "image"},
                {label: "Text", name: "body", widget: "markdown"}]},]}
          - {label: "Story", name: ourStory, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Intro", name: "intro", widget: text},
              {label: "Content", name: "content", widget: "list", fields: [
                {label: "Text", name: "ourStoryText", widget: "text"}]}]}
          - {label: "Our Team", name: ourTeam, widget: list, fields: [
              {label: "Avatar", name: "avatar", widget: "image"},
              {label: "Name", name: "name", widget: "string"},
              {label: "Role", name: "role", widget: "string"},
              {label: "About", name: "about", widget: "text"}]}
          - {label: "Why Stratobooster", name: "whyStrato", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Reasons", name: "reasons", widget: "list", fields: [
                {label: "Image", name: "reasonImage", widget: "image"},
                {label: "Text", name: "reasonText", widget: "text"}]},]}
          - {label: "In The Press", name: "inPress", widget: "list", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: text},
              {label: "Link To Story", name: "link", widget: string}]}
          - {label: "Footer", name: "footer", widget: "object", fields: [
              {label: "Email", name: "email", widget: string},
              {label: "ButtonText", name: "buttonText", widget: string},
              {label: "ButtonLink", name: "buttonLink", widget: string}]}
